import Header2 from '../components/Header2'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <div className='bg-slate-100'>
        <Header2/>
        {children}
        </div>
  )
}
